#-------------------------------
# General Site Settings

# title: Think Loragil | Hezi Ben-David
description: Thinker // Designer // Loragil
email: hezi.bd@gmail.com

# NOTE: The Logo and Background image are defined in the all.sass document.

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'website Designer, banners etc'

banners:
- {name: Western Galilee College, folder: 'banner01', file: 'banners/banner01.html'}
- {name: Bluran3D, folder: 'banner02', file: 'banners/banner02.html'}
- {name: Tivoni, folder: 'banner03', file: 'banners/banner03.html'}
- {name: Western Galilee College, folder: 'banner04', file: 'banners/banner04.html'}
- {name: Western Galilee College, folder: 'banner05', file: 'banners/banner05.html'}
- {name: Western Galilee College, folder: 'banner06', file: 'banners/banner06.html'}
- {name: Western Galilee College, folder: 'banner07', file: 'banners/banner07.html'}
- {name: Ben Gurion University, folder: 'banner08', file: 'banners/banner08.html'}
- {name: Ben Gurion University, folder: 'banner09' , file: 'banners/banner09.html'}
- {name: Port of Haifa, folder: 'banner10', file: 'banners/banner10.html'}
- {name: Quality Mark, folder: 'banner11', file: 'banners/banner11.html'}
- {name: Ben Gurion University, folder: 'banner12', file: 'banners/banner12.html'}
